### ISSUE TITLE
Deployment of Live demo link.

### ISSUE THREAD

**Issue by saikatgpae** [saikatgpae/saikat-portfolio#10]
As the live demo link already deployed in README.md, as per instruction creating an issue with live link.
https://saikatgpae.github.io/saikat-portfolio/

**Comment by zieeco** [comment]
Hi @saikatgpae,


Great job so far 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️


## Required Changes ♻️
_Check the comments below._


:point_right: **As it is not advisable to work directly from your main branch, please kindly open a new PR for this present milestone and update your readme to be more professional, and add the link to this issue so that the next reviewer would continue with the review to reduce any conflict that may arise..**

- [x] Please, kindly add a "Getting started " header section and add some instructions on how users can have your project running locally on their machine.
- [x] Please, kindly add the "Contributing" header section and add necessary content making sure you add the link to the issue page of your portfolio Github repository to help the user navigate to the issues page from your readme file.
- [x] Your project name should be best left as 'Portfolio' as the name actually points to the mobile version whereas the portfolio is now both the mobile and desktop version. please kindly fix the name issue to make your readme more professional.
- [x] Please, kindly make the authors singular since you didn't add other partners that have collaborated with you on the project to make your readme appear more professional.


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by saikatgpae** [comment]
Changed the necessary as per the instruction.
